# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60591d1c7a12358eb16573055532d8e27dc37000cde4a6a2de31e525ad1e2c8ea2db2e8f1508bfd32db1a232977142d0570214e4f8e45b17b87b1f1967182638

test:
  secret_key_base: 7498d0d7bc102667985228ea9ae7d3197b61f26f4fde2b224265057af0f7f738762535588188b8fa8db542e2ec4ea62763eed093b543e3b427aa9f6c402dab7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
